//
//  JString.swift
//  Bartleby
//
// THIS FILE AS BEEN GENERATED BY BARTLEBYFLEXIONS for b@bartlebys.org
// DO NOT MODIFY THIS FILE YOUR MODIFICATIONS WOULD BE ERASED ON NEXT GENERATION!
//
// Copyright (c) 2016  Bartleby's | https://bartlebys.org  All rights reserved.
//
import Foundation
#if !USE_EMBEDDED_MODULES
import Alamofire
import ObjectMapper
#endif

// MARK: Bartleby's Core: String Primitive Wrapper. (Used for example to pass task Arguments)
@objc(JString) public class JString : JObject{

    // Universal type support
    override public class func typeName() -> String {
        return "JString"
    }

	//the embedded String
	public var string:String? {	 
	    didSet { 
	       if string != oldValue {
	            self.provisionChanges(forKey: "string",oldValue: oldValue,newValue: string) 
	       } 
	    }
	}



    // MARK: Mappable

    required public init?(_ map: Map) {
        super.init(map)
    }

    override public func mapping(map: Map) {
        super.mapping(map)
        self.disableSupervisionAndCommit()
		self.string <- ( map["string"] )
        self.enableSuperVisionAndCommit()
    }


    // MARK: NSSecureCoding

    required public init?(coder decoder: NSCoder) {
        super.init(coder: decoder)
        self.disableSupervisionAndCommit()
		self.string=String(decoder.decodeObjectOfClass(NSString.self, forKey:"string") as NSString?)

        self.enableSuperVisionAndCommit()
    }

    override public func encodeWithCoder(coder: NSCoder) {
        super.encodeWithCoder(coder)
		if let string = self.string {
			coder.encodeObject(string,forKey:"string")
		}
    }


    override public class func supportsSecureCoding() -> Bool{
        return true
    }


    required public init() {
        super.init()
    }

    // MARK: Identifiable

    override public class var collectionName:String{
        return "jStrings"
    }

    override public var d_collectionName:String{
        return JString.collectionName
    }


}

