//
//  Report.swift
//  Bartleby
//
// THIS FILE AS BEEN GENERATED BY BARTLEBYFLEXIONS for [Benoit Pereira da Silva] (https://pereira-da-silva.com/contact)
// DO NOT MODIFY THIS FILE YOUR MODIFICATIONS WOULD BE ERASED ON NEXT GENERATION!
//
// Copyright (c) 2016  [Bartleby's org] (https://bartlebys.org)   All rights reserved.
//
import Foundation
#if !USE_EMBEDDED_MODULES
	import Alamofire
	import ObjectMapper
#endif

// MARK: Bartleby's Core: a Report object that can be used for analytics and support purposes
@objc(Report) open class Report : Report{

    // Universal type support
    override open class func typeName() -> String {
        return "Report"
    }

	//The document Metadata (contains highly sensitive data)
	dynamic open var metadata:DocumentMetadata?

	//A collection logs
	dynamic open var logs:[LogEntry] = [LogEntry]()

	//A collection metrics
	dynamic open var metrics:[Metrics] = [LogEntry]()

    // MARK: - Exposed (Bartleby's KVC like generative implementation)

    /// Return all the exposed instance variables keys. (Exposed == public and modifiable).
    override open var exposedKeys:[String] {
        var exposed=super.exposedKeys
        exposed.append(contentsOf:["metadata","logs","metrics"])
        return exposed
    }


    /// Set the value of the given key
    ///
    /// - parameter value: the value
    /// - parameter key:   the key
    ///
    /// - throws: throws an Exception when the key is not exposed
    override open func setExposedValue(_ value:Any?, forKey key: String) throws {
        switch key {
            case "metadata":
                if let casted=value as? DocumentMetadata{
                    self.metadata=casted
                }
            case "logs":
                if let casted=value as? [LogEntry]{
                    self.logs=casted
                }
            case "metrics":
                if let casted=value as? [Metrics]{
                    self.metrics=casted
                }
            default:
                return try super.setExposedValue(value, forKey: key)
        }
    }


    /// Returns the value of an exposed key.
    ///
    /// - parameter key: the key
    ///
    /// - throws: throws Exception when the key is not exposed
    ///
    /// - returns: returns the value
    override open func getExposedValueForKey(_ key:String) throws -> Any?{
        switch key {
            case "metadata":
               return self.metadata
            case "logs":
               return self.logs
            case "metrics":
               return self.metrics
            default:
                return try super.getExposedValueForKey(key)
        }
    }
    // MARK: - Mappable

    required public init?(map: Map) {
        super.init(map:map)
    }

    override open func mapping(map: Map) {
        super.mapping(map: map)
        self.silentGroupedChanges {
			self.metadata <- ( map["metadata"] )
			self.logs <- ( map["logs"] )
			self.metrics <- ( map["metrics"] )
        }
    }


    // MARK: - NSSecureCoding

    required public init?(coder decoder: NSCoder) {
        super.init(coder: decoder)
        self.silentGroupedChanges {
			self.metadata=decoder.decodeObject(of:DocumentMetadata.self, forKey: "metadata") 
			self.logs=decoder.decodeObject(of: [NSArray.classForCoder(),LogEntry.classForCoder()], forKey: "logs")! as! [LogEntry]
			self.metrics=decoder.decodeObject(of: [NSArray.classForCoder(),Metrics.classForCoder()], forKey: "metrics")! as! [Metrics]
        }
    }

    override open func encode(with coder: NSCoder) {
        super.encode(with:coder)
		if let metadata = self.metadata {
			coder.encode(metadata,forKey:"metadata")
		}
		coder.encode(self.logs,forKey:"logs")
		coder.encode(self.metrics,forKey:"metrics")
    }

    override open class var supportsSecureCoding:Bool{
        return true
    }

     required public init() {
        super.init()
    }

    // MARK: Identifiable

    override open class var collectionName:String{
        return "reports"
    }

    override open var d_collectionName:String{
        return Report.collectionName
    }
}