//
//  Trigger.swift
//  Bartleby
//
// THIS FILE AS BEEN GENERATED BY BARTLEBYFLEXIONS for [Benoit Pereira da Silva] (https://pereira-da-silva.com/contact)
// DO NOT MODIFY THIS FILE YOUR MODIFICATIONS WOULD BE ERASED ON NEXT GENERATION!
//
// Copyright (c) 2016  [Bartleby's org] (https://bartlebys.org)   All rights reserved.
//
import Foundation
#if !USE_EMBEDDED_MODULES
	import Alamofire
	import ObjectMapper
#endif

// MARK: Bartleby's Core: a Trigger encapsulates a bunch of that's modelizes a state transformation
@objc(Trigger) open class Trigger : UnManagedModel {


	//The index is injected server side (each observationUID) has it own counter)
	dynamic open var index:Int = -1

	//The dataSpace UID
	dynamic open var spaceUID:String?

	//The observation UID
	dynamic open var observationUID:String?

	//The user.UID of the sender
	dynamic open var senderUID:String?

	//The UID of the instance of Bartleby client that has created the trigger.
	dynamic open var runUID:String?

	//The action that has initiated the trigger
	dynamic open var origin:String?

	//The targetted collection name
	dynamic open var targetCollectionName:String = ""

	//The server side creation date ( informative, use index for ranking)
	dynamic open var creationDate:Date?

	//The action name
	dynamic open var action:String = ""

	//A coma separated UIDS list
	dynamic open var UIDS:String = ""

	//The sseDbProcessingDuration is computed server side in SSE context only not when calling Triggers endpoints (it can be used for QOS computation)
	dynamic open var sseDbProcessingDuration:Double = -1

	//A collection of JSON payload
	dynamic open var payloads:[[String:Any]]?


    // MARK: - Mappable

    required public init?(map: Map) {
        super.init(map:map)
    }

    override open func mapping(map: Map) {
        super.mapping(map: map)
        self.quietChanges {
			self.index <- ( map["index"] )
			self.spaceUID <- ( map["spaceUID"] )
			self.observationUID <- ( map["observationUID"] )
			self.senderUID <- ( map["senderUID"] )
			self.runUID <- ( map["runUID"] )
			self.origin <- ( map["origin"] )
			self.targetCollectionName <- ( map["targetCollectionName"] )
			self.creationDate <- ( map["creationDate"], ISO8601DateTransform() )
			self.action <- ( map["action"] )
			self.UIDS <- ( map["UIDS"] )
			self.sseDbProcessingDuration <- ( map["sseDbProcessingDuration"] )
			self.payloads <- ( map["payloads"] )
        }
    }

     required public init() {
        super.init()
    }
}